THOUGHT_INTERVAL_MIN = 1
THOUGHT_INTERVAL_MAX = 5
REFLECTION_INTERVAL = 900  # 15 min
ENERGY_DECAY = 0.01
MOOD_DRIFT = 0.02
MAX_MEMORY_SHORT = 50


ALPHABET = list("abcdefghijklmnopqrstuvwxyz ")
VALID_SHORT = {"i", "a", "in", "on", "to", "of", "me", "us", "be", "ye"}


LEARNING_RATE = 0.3
DECAY_RATE = 0.01
EXPANSION_THRESHOLD = 1.0
#MAX_GENERATION_LENGTH = 6
MIN_LENGTH = 1
MAX_LENGTH = 12
ROOT = "__root__"