THOUGHT_INTERVAL_MIN = 5
THOUGHT_INTERVAL_MAX = 20
REFLECTION_INTERVAL = 900  # 15 min
ENERGY_DECAY = 0.01
MOOD_DRIFT = 0.02
MAX_MEMORY_SHORT = 50


ALPHABET = list("abcdefghijklmnopqrstuvwxyz ")
LEARNING_RATE = 0.3
DECAY_RATE = 0.001
EXPANSION_THRESHOLD = 0.8
#MAX_GENERATION_LENGTH = 6
MIN_LENGTH = 1
MAX_LENGTH = 12