ATICKSPEED = 1 #Per second for Agent
WTICKSPEED = 10 # Per second for World

WORLDLIMITS = [(0, 800), (0, 600)]
FOV = 120
RAYDENSITY = 70
MAXDISTANCE = 200
RAYSTEPSIZE = 0.7
HEADANGLE = 0

ROTATIONSPEED = 25 # Deg to  Radian

LOW_ENTITY_THRESHOLD = 1
HIGH_ENTITY_THRESHOLD = 10